name: For Each Env
description: Do Terraform operation for each environment

inputs:
  operation:
    description: Operation to be performed for each environment
    required: true

outputs:
  stdout:
    description: STDOUT stream of Terraform command
    value: ${{ steps.for-each-env.outputs.stdout }}
  stderr:
    description: STDERR stream of Terraform command
    value: ${{ steps.for-each-env.outputs.stderr }}
  exitcode:
    description: Exit code of Terraform command
    value: ${{ steps.for-each-env.outputs.exitcode }}

runs:
  using: "composite"
  steps:
    - name: Terraform init cache
      uses: actions/cache@v3
      with:
        path: environments/**/.terraform/*
        key: terraform-init-environments
    - name: For each env
      id: for-each-env
      shell: bash
      run: |
        for environment in $(find environments -type d -maxdepth 1 -mindepth 1); do
          cd $environment
          if ! terraform ${{ inputs.operation }}; then
            exit $?
          fi
          cd -
        done
