name: revoke-vpn-client-cert

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment where VPN is deployed
        required: true
        options:
          - dev
          - stg
          - prod
      client_name:
        type: string
        description: Name of client certificate to be revoked
        required: true

jobs:
  revoke-vpn-client-cert:
    name: Revoke VPN client certificate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: ${{ github.event.inputs.env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/go-api-template-github-actions-cicd
          role-session-name: GitHubWorkflowCI
      - name: Setup EasyRSA
        uses: ./.github/actions/setup-easyrsa
      - name: Revoke client cert
        run: make revoke-client-cert CLIENT_CRT_NAME=${{ github.event.inputs.client_name }}
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "gh actions auto-commit: revoke vpn client cert for ${{ github.event.inputs.client_name }}"
